bookshopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("loginapp.urls")),
    path("owner/",include("owner.urls")),
    path("customer/",include("customer.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from customer import views

urlpatterns = [
    path("home", views.HomeView.as_view(), name="home"),
    path("books/list", views.BooksListView.as_view(), name="all-books"),
    path("books/<int:id>", views.BookDetailView.as_view(), name="book-details"),
    path("books/<int:id>/carts/add", views.AddToCartView.as_view(), name="addto-cart"),
    path("carts/all", views.MyCartView.as_view(), name="mycart"),
    path("carts/placeorder/<int:cid>/<int:pid>", views.PlaceOrderView.as_view(), name="place-order"),
    path("carts/remove/<int:id>", views.delete_product, name="remove-item"),
    path("signout", views.SignOutView.as_view(), name="signout"),

]

owner/urls.py
from django.urls import path
from owner import views


urlpatterns=[
    path("dashboard", views.AdminDashBoardView.as_view(), name="dashboard"),
    path("category",views.CategoryAddView.as_view(), name="category"),
    path("book",views.BookAddView.as_view(), name="book"),
    path("category/list", views.CategoryListView.as_view(), name="categorylist"),
    path("category/change/<int:id>", views.CategoryEditView.as_view(), name="category-edit"),
    path("category/remove/<int:id>",views.delete_category,name="remove-category"),
    path("book/list", views.BookListView.as_view(), name="booklist"),
    path("book/remove/<int:id>",views.delete_book,name="remove-book"),
    path("book/details/<int:id>",views.BookDetailView.as_view(),name="book-detail"),
    path("book/change/<int:id>",views.BookEditView.as_view(),name="book-edit"),
    path("orders/latest", views.OrdersListView.as_view(), name="neworders"),
    path("signout", views.SignOutView.as_view(), name="signout"),

]

customer/models.py
from django.db import models

# Create your models here.

owner/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Categories(models.Model):
    category_name = models.CharField(max_length=200, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.category_name


class Books(models.Model):
    book_name = models.CharField(max_length=200, unique=True)
    author=models.CharField(max_length=200, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images", null=True)
    price = models.PositiveIntegerField()
    description = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.book_name


class Carts(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    options = (
        ("in-cart", "in-cart"),
        ("order-placed", "order-placed"),
        ("cancelled", "cancelled")
    )
    status = models.CharField(max_length=120, choices=options, default="in-cart")
    qty = models.PositiveIntegerField(default=1)


class Orders(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    options = (
        ("order-placed", "order-placed"),
        ("dispatched", "dispatched"),
        ("in-transit", "in-transit"),
        ("delivered", "delivered"),
        ("cancelled", "cancelled")
    )
    status = models.CharField(max_length=120, choices=options, default="order-placed")
    delivery_address = models.CharField(max_length=250, null=True)
    expected_delivery_date = models.DateTimeField(null=True)


class Reviews(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.CharField(max_length=120)
    rating = models.PositiveIntegerField()

customer/forms.py
from django import forms

class CartForm(forms.Form):
    qty=forms.IntegerField(widget=forms.NumberInput(attrs={"class":"form-control"}))


class OrderForm(forms.Form):
    delivery_address=forms.CharField(widget=forms.Textarea(attrs={"class":"form-control"}))

customer/views.py
from django.shortcuts import render,redirect
from loginapp import forms
from customer import forms
from django.contrib import messages
from django.urls import reverse_lazy
from owner.models import Books,Carts,Orders
from django.views.generic import TemplateView,View,DetailView,FormView,ListView
from django.contrib.auth import logout
# Create your views here.


class HomeView(TemplateView):
    template_name: str="home.html"




class BooksListView(View):

    def get(self, request, *args, **kwargs):
        all_books = Books.objects.all()
        return render(request, "all-books.html", {"books": all_books})


class BookDetailView(DetailView):
    template_name: str="book-details.html"
    model=Books
    context_object_name="book"
    pk_url_kwarg: str="id"



class AddToCartView(FormView):
    template_name: str="addto-cart.html"
    form_class=forms.CartForm

    def get(self,request,*args,**kwargs):
        id=kwargs.get("id")
        book=Books.objects.get(id=id)

        return render(request,self.template_name,{"form":forms.CartForm(),"book":book})

    def post(self,request,*args,**kwargs):
        id=kwargs.get("id")
        book=Books.objects.get(id=id)
        qty=request.POST.get("qty")
        user=request.user
        Carts.objects.create(book=book,user=user,qty=qty)
        # messages.success(request,"successfully your product hasbeen added to cart")
        return redirect("home")

class MyCartView(ListView):    #cart listview
    model=Carts
    template_name: str="cart-list.html"
    context_object_name="carts"

    def get_queryset(self):
        return Carts.objects.filter(user=self.request.user).order_by("-created_date")


class PlaceOrderView(FormView):
    template_name: str = "place-order.html"
    form_class = forms.OrderForm

    def post(self, request, *args, **kwargs):
        cart_id = kwargs.get("cid")
        product_id = kwargs.get("pid")
        cart = Carts.objects.get(id=cart_id)
        book = Books.objects.get(id=product_id)
        user = request.user
        delivery_address = request.POST.get("delivery_address")
        Orders.objects.create(book=book,
                              user=user,
                              delivery_address=delivery_address

                              )
        cart.status = "order-placed"
        cart.save()
        # messages.success(request, "successfully your order hasbeen placed")
        return redirect("home")

def delete_product(request,*args,**kwargs):  #product status:cancelled only
    id=kwargs.get("id")
    cart=Carts.objects.get(id=id)
    cart.status="cancelled"
    cart.save()
    return redirect("mycart")


class SignOutView(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("login")

customer/templates/addto-cart.html
{%extends 'basepage.html'%}
{%block body_block%}

<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-6 mt-5">
            <div class="card" style="width: 25rem;">
                <!-- Product image-->
                <img class="card-img-top" src="{{book.image.url}}" alt="..." height="">
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{book.book_name}}</h5>
                        <!-- Product price-->
                        ${{book.price}}

                        <p>{{book.description}}</p>
                        <p>{{book.category}}</p>
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">

                </div>
            </div>
        </div>
        <div class="col-4 mt-5">
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}} <br>
                <button type="submit">Add to cart</button>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4"></div>
        <div class="col-4"></div>
    </div>
</div>

{%endblock%}

customer/templates/all-books.html
{%extends 'basepage.html'%}
{%block body_block%}




<div class="container">
    <h1>all books to view and shop</h1>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {%for book in books%}

        <div class="col mb-5 mt-5">
            <div class="card" style="width: 25rem;">
                <!-- Product image-->
                <img class="card-img-top" src="{{book.image.url}}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{book.book_name}}</h5>
                        <!-- Product price-->
                        ${{book.price}}
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'book-details' book.id%}">View</a></div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>

</div>
{%endblock%}

customer/templates/basepage.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Book store</title>
	<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<!--
Holiday Template
http://www.templatemo.com/tm-475-holiday
-->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>
  <link href="{%static 'css/font-awesome.min.css'%}" rel="stylesheet">
  <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{%static 'css/bootstrap-datetimepicker.min.css'%}" rel="stylesheet">
  <link href="{%static 'css/flexslider.css'%}" rel="stylesheet">
  <link href="{%static 'css/templatemo-style.css'%}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body class="tm-white-bg">
  {%csrf_token%}
  	<!-- Header -->
  	<div class="tm-header">
  		<div class="container">
  			<div class="row">
  				<div class="col-lg-6 col-md-4 col-sm-3 tm-site-name-container">
					<a href="{%url 'home'%}" class="tm-site-name">BOOKS <em>SHOPIE</em></a>
  				</div>
	  			<div class="col-lg-6 col-md-8 col-sm-9">
	  				<div class="mobile-menu-icon">
		              <i class="fa fa-bars"></i>
		            </div>
	  				<nav class="tm-nav">
						<ul>
							<li><a href="{%url 'home'%}">Home</a></li>
<!--							<li><a style="font-size:22px" class="fa">&#xf07a;</a></li>-->

							<li><a href="{%url 'all-books'%}">Books</a></li>
<!--							<li><a href="about.html">About</a></li>-->
<!--							<li><a href="carts.html">My Cart</a></li>-->
<!--							<li><a href="{%url 'mycart' %}" style="font-size:22px" class="fa">&#xf07a;</a></li>-->
							<li>
								<form class="d-flex">
<!--                        			<a href="{%url 'mycart'%}" class="btn btn-outline-dark" type="submit">-->
                            			<i class="bi-cart-fill me-1"></i>

										<a href="{%url 'mycart' %}" style="font-size:20px" class="fa">&#xf07a;
                            			<span class="badge bg-dark text-white ms-1 rounded-pill">

                                			{{request.user.carts_set.all.count}}

                            			</span>
										</a>
									</a>
                    			</form>
							</li>

							<li><a href="{%url 'login' %}">Logout</a></li>
						</ul>
					</nav>
	  			</div>
  			</div>
  		</div>
  	</div>




	{%block body_block%}


  	{%endblock%}










<!--  <footer class="tm-black-bg">-->
<!--		<div class="container">-->
<!--			<div class="row">-->
<!--				<p class="tm-copyright-text">Copyright &copy; 2084 Your Company Name</p>-->
<!--			</div>-->
<!--		</div>-->
<!--	</footer>-->





	<script type="text/javascript" src="{%static 'js/jquery-1.11.2.min.js'%}"></script>      		<!-- jQuery -->
  	<script type="text/javascript" src="{%static 'js/moment.js'%}"></script>							<!-- moment.js -->
	<script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>					<!-- bootstrap js -->
	<script type="text/javascript" src="{%static 'js/bootstrap-datetimepicker.min.js'%}"></script>	<!-- bootstrap date time picker js, http://eonasdan.github.io/bootstrap-datetimepicker/ -->
	<script type="text/javascript" src="{%static 'js/jquery.flexslider-min.js'%}"></script>
<!--
	<script src="js/froogaloop.js"></script>
	<script src="js/jquery.fitvid.js"></script>
-->
   	<script type="text/javascript" src="{%static 'js/templatemo-script.js'%}"></script>      		<!-- Templatemo Script -->
	<script>
		// HTML document is loaded. DOM is ready.
		$(function() {

			$('#hotelCarTabs a').click(function (e) {
			  e.preventDefault()
			  $(this).tab('show')
			})

        	$('.date').datetimepicker({
            	format: 'MM/DD/YYYY'
            });
            $('.date-time').datetimepicker();

			// https://css-tricks.com/snippets/jquery/smooth-scrolling/
		  	$('a[href*=#]:not([href=#])').click(function() {
			    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
			      var target = $(this.hash);
			      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
			      if (target.length) {
			        $('html,body').animate({
			          scrollTop: target.offset().top
			        }, 1000);
			        return false;
			      }
			    }
		  	});
		});

		// Load Flexslider when everything is loaded.
		$(window).load(function() {
			// Vimeo API nonsense

/*
			  var player = document.getElementById('player_1');
			  $f(player).addEvent('ready', ready);

			  function addEvent(element, eventName, callback) {
			    if (element.addEventListener) {
			      element.addEventListener(eventName, callback, false)
			    } else {
			      element.attachEvent(eventName, callback, false);
			    }
			  }

			  function ready(player_id) {
			    var froogaloop = $f(player_id);
			    froogaloop.addEvent('play', function(data) {
			      $('.flexslider').flexslider("pause");
			    });
			    froogaloop.addEvent('pause', function(data) {
			      $('.flexslider').flexslider("play");
			    });
			  }
*/



			  // Call fitVid before FlexSlider initializes, so the proper initial height can be retrieved.
/*

			  $(".flexslider")
			    .fitVids()
			    .flexslider({
			      animation: "slide",
			      useCSS: false,
			      animationLoop: false,
			      smoothHeight: true,
			      controlNav: false,
			      before: function(slider){
			        $f(player).api('pause');
			      }
			  });
*/




//	For images only
		    $('.flexslider').flexslider({
			    controlNav: false
		    });


	  	});
	</script>
 </body>
 </html>

customer/templates/book-details.html
{%extends 'basepage.html'%}
{%block body_block%}

<div class="container">
    <div class="row mt-5">
        <div class="col-3"></div>
        <div class="col-6">

            <div class="card" style="width: 40rem;">
                <!-- Product image-->
                <img class="card-img-top" src="{{book.image.url}}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{book.book_name}}</h5><br>
                        <!-- Product price-->
                        Price: ${{book.price}}<br><br>
                        <p>Book Genre: {{book.category}}</p><br>
                        <p>{{book.description}}</p>

                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'addto-cart' book.id %}">AddtoCart</a></div>

                </div>
            </div>
            
        </div>
        <div class="col-3"></div>
    </div>
</div>
{%endblock%}

customer/templates/cart-list.html
{%extends 'basepage.html'%}
{%block body_block%}

<div class="container mt-5 ">
    <h3 style="font-family: 'Times New Roman', Times, serif; color: #202639;"><strong>CART ITEMS</strong></h3>

    <div class="row mt-5">
        {%for cart in carts%}
        
        <div class="col-3"></div>

        <div class="col-4 mt-5 text-center">
            <div class="card" style="width: 24rem">
                <!-- Product image-->
                <img class="card-img-top" src="{{cart.book.image.url}}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{cart.book.book_name}}</h5>
                        <!-- Product price-->
                        ${{cart.book.price}}
                    </div>
                </div>


            </div>
        </div>
        <div class="col-2 mt-5">
            <h5>Quantity :    {{cart.qty}} </h5>
            <h5>Order Status: {{cart.status}} </h5>

        </div>

        <div class="col-3 mt-5">
            {%if cart.status != "order-placed" and cart.status != "cancelled" %}
                <a href="{%url 'remove-item' cart.id %}" class="btn btn-outline-danger"><h5>Remove</h5></a>
            {%endif%}
            {%if cart.status != "order-placed" and cart.status != "cancelled" %}
                <a href="{%url 'place-order' cart.id cart.book.id %}" class="btn btn-outline-success"><h5>Checkout</h5></a>
            {%endif%}

        </div>
        {%endfor%}
    </div>

</div>

{%endblock%}

customer/templates/place-order.html
{%extends 'basepage.html'%}
{%block body_block%}

<div class="container">
    <div class="row">
        <div class="col-4"></div>

        <div class="col-4 mt-5">
            
            <form action="" method="post">
                {%csrf_token%}
                {{form.as_p}} <br>
                <button type="submit">Order</button>
            </form>

        </div>


        <div class="col-4">
            
        </div>
    </div>

    <div class="row">
        <div class="col-4"></div>
        <div class="col-4"></div>
        <div class="col-4"></div>
    </div>
</div>

{%endblock%}